name: Nexus3DS

on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number || github.run_id }}
  cancel-in-progress: true

jobs:
  Nexus3DS:
    runs-on: ubuntu-latest
    container:
      image: meastes/devkitarm-3ds:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install build requirements
        run: |
          apt update
          apt install ninja-build --force-y
      - name: Download and install dependencies
        run : |
          apt install build-essential git libsdl2-dev libvorbis-dev libogg-dev libtheora-dev -y   
      - name: Build Sonic Nexus for the Nintendo 3DS
        run: make -f Makefile.3ds
      - name: Move artifacts
        run: |
          mkdir artifacts
          mv ./build_3ds ./artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Nexus 3DS
          path: artifacts                       
